name: Android Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
    
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.5'
        channel: 'stable'
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Enable Android toolchain
      run: |
        flutter doctor
        flutter config --enable-android
    
    - name: Accept Android licenses
      run: yes | flutter doctor --android-licenses || true
    
    - name: Clean build
      run: flutter clean
    
    - name: Get dependencies again
      run: flutter pub get
    
    - name: Build Android APK (Debug first)
      run: flutter build apk --debug
    
    - name: Build Android APK (Release)
      run: flutter build apk --release --no-shrink
    
    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: TapCare-Android-Debug-APK
        path: build/app/outputs/flutter-apk/app-debug.apk
        retention-days: 30
    
    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      with:
        name: TapCare-Android-Release-APK
        path: build/app/outputs/flutter-apk/app-release.apk
        retention-days: 30
